FROM node:20-alpine AS base

# Stage 1: Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat

# -- CLOUD RUN STANDARDS REMINDER --
# If you add dependencies with native bindings (e.g., sharp, bcrypt, Prisma),
# you MUST include the required Alpine Linux packages here to ensure container dependency parity.
# Example: 
# RUN apk add --no-cache openssl python3 make g++ 

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
RUN npm ci

# Stage 2: Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Disable Next.js telemetry during the build
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# Stage 3: Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
# Disable Next.js telemetry during runtime
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
# Copy the standalone output generated by Next.js
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
# Copy the public directory for static assets
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

# Expose port 8080 for Google Cloud Run
EXPOSE 8080

# Cloud Run requires the server to listen on the port defined by the PORT environment variable
ENV PORT=8080
ENV HOSTNAME="0.0.0.0"

# server.js is created by `next build` from the standalone output
CMD ["node", "server.js"]
